name: app
description: Flutter Architecture Blueprints project.
version: 1.0.0+1

publish_to: 'none'

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: '>=3.0.5'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # For Google and Firebase
  firebase_core: ^1.17.0
  firebase_auth: ^3.6.2
  google_sign_in: ^5.4.0
  firebase_crashlytics: ^2.8.0
  firebase_performance: ^0.7.1+2

  # For Architecture
  flutter_hooks: ^0.18.0
  hooks_riverpod: ^1.0.3
  rxdart: ^0.27.3

  # For Networking
  dio: ^4.0.1
  dio_firebase_performance: ^0.3.1-dev.3
  retrofit: ^2.0.1
  # For User-Agent Client Hints
  ua_client_hints: ^1.1.0

  # For Model
  json_serializable: ^6.1.4
  freezed_annotation: ^1.0.0

  # For Navigation
  auto_route: ^3.2.4

  # For DateTime
  intl: ^0.17.0

  # Convert between Enum and String
  enum_to_string: ^2.0.1

  # For UIs
  gap: ^2.0.0
  cupertino_icons: ^1.0.3
  google_fonts: ^2.1.0
  flutter_svg: 1.1.3
  bubble_tab_indicator: "^0.1.6"
  toggle_switch: ^1.4.0
  font_awesome_flutter: ^10.1.0
  scrolls_to_top: ^1.1.1
  expandable: ^5.0.1

  # For Data
  shared_preferences: ^2.0.12
  sqflite: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.0.4

  # For Networking
  retrofit_generator: ^2.0.0+1

  # For Assets
  flutter_gen_runner: ^4.1.5

  # For Navigation
  auto_route_generator: ^3.1.0

  # For Model
  freezed: ^1.0.0

  # For Analyzer
  flutter_lints: ^2.0.0

  # For Testing
  mocktail: ^0.2.0
  mocktail_image_network: ^0.2.0

flutter_gen:
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/svgs/

  fonts:
    - family: Rotunda
      fonts:
        - asset: assets/fonts/Rotunda-Bold.otf
          weight: 700
